#[
autogenerated by docgen
loc: /home/runner/work/nim-lang.Nim/nim-lang.Nim/lib/std/jsbigints.nim(141, 3)
rdoccmd: 
]#
import std/assertions
import "/home/runner/work/nim-lang.Nim/nim-lang.Nim/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/nim-lang.Nim/nim-lang.Nim/lib/std/jsbigints.nim", 141, 3).}:
  doAssert (big"999" shr big"2") == big"249"

